<?php

namespace ContainerIDTr2d1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessDeniedEventListenerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\EventListener\AccessDeniedEventListener' shared autowired service.
     *
     * @return \App\EventListener\AccessDeniedEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/AccessDeniedEventListener.php';

        return $container->privates['App\\EventListener\\AccessDeniedEventListener'] = new \App\EventListener\AccessDeniedEventListener();
    }
}
