<?php

namespace ContainerIDTr2d1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewFileControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\ViewFileController' shared autowired service.
     *
     * @return \App\Controller\ViewFileController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/UserServices/CheckCredentials.php';
        include_once \dirname(__DIR__, 4).'/src/UserServices/UserService.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ViewFileController.php';

        $container->services['App\\Controller\\ViewFileController'] = $instance = new \App\Controller\ViewFileController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\ViewFileController', $container));

        return $instance;
    }
}
