<?php

namespace ContainerElEQOhT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E3spfHLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E3spfHL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E3spfHL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'file' => ['privates', '.errored..service_locator.E3spfHL.App\\Entity\\File', NULL, 'Cannot autowire service ".service_locator.E3spfHL": it references class "App\\Entity\\File" but no such service exists.'],
        ], [
            'em' => '?',
            'file' => 'App\\Entity\\File',
        ]);
    }
}
