<?php

namespace ContainerNR9GnZG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EJAYC0ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EJAYC0Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EJAYC0Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'catalog' => ['privates', '.errored..service_locator.EJAYC0Z.App\\Entity\\Catalog', NULL, 'Cannot autowire service ".service_locator.EJAYC0Z": it references class "App\\Entity\\Catalog" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.EJAYC0Z.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.EJAYC0Z": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'catalog' => 'App\\Entity\\Catalog',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
