<?php

namespace ContainerNR9GnZG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatalog3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EJAYC0Z.App\Entity\Catalog' shared service.
     *
     * @return \App\Entity\Catalog
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.EJAYC0Z": it references class "App\\Entity\\Catalog" but no such service exists.');
    }
}
