<?php

namespace ContainerH6UzAQJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D3hcD5zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D3hcD5z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D3hcD5z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'catalog' => ['privates', '.errored..service_locator.D3hcD5z.App\\Entity\\Catalog', NULL, 'Cannot autowire service ".service_locator.D3hcD5z": it references class "App\\Entity\\Catalog" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'catalog' => 'App\\Entity\\Catalog',
            'em' => '?',
        ]);
    }
}
