<?php

namespace ContainerH6UzAQJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IlNZDlrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IlNZDlr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IlNZDlr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'catalog' => ['privates', '.errored..service_locator.IlNZDlr.App\\Entity\\Catalog', NULL, 'Cannot autowire service ".service_locator.IlNZDlr": it references class "App\\Entity\\Catalog" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'onixFile_directory' => ['privates', '.value.XibwmKv', 'get_Value_XibwmKvService', true],
            'user' => ['privates', '.errored..service_locator.IlNZDlr.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.IlNZDlr": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'catalog' => 'App\\Entity\\Catalog',
            'em' => '?',
            'onixFile_directory' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
