<?php

namespace ContainerY9lee6f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TX_ZJtaService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.TX.zJta' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TX.zJta'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'file' => ['privates', '.errored..service_locator.TX.zJta.App\\Entity\\File', NULL, 'Cannot autowire service ".service_locator.TX.zJta": it references class "App\\Entity\\File" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.TX.zJta.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.TX.zJta": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'em' => '?',
            'file' => 'App\\Entity\\File',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
