<?php

namespace ContainerY9lee6f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLastLoginEventListenerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\EventListener\LastLoginEventListener' shared autowired service.
     *
     * @return \App\EventListener\LastLoginEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/LastLoginEventListener.php';

        return $container->privates['App\\EventListener\\LastLoginEventListener'] = new \App\EventListener\LastLoginEventListener(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
