<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOmQOgwi\App_KernelPantherDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOmQOgwi/App_KernelPantherDebugContainer.php') {
    touch(__DIR__.'/ContainerOmQOgwi.legacy');

    return;
}

if (!\class_exists(App_KernelPantherDebugContainer::class, false)) {
    \class_alias(\ContainerOmQOgwi\App_KernelPantherDebugContainer::class, App_KernelPantherDebugContainer::class, false);
}

return new \ContainerOmQOgwi\App_KernelPantherDebugContainer([
    'container.build_hash' => 'OmQOgwi',
    'container.build_id' => '896dab8f',
    'container.build_time' => 1636548969,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOmQOgwi');
