<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRMW2JcO\App_KernelPantherDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRMW2JcO/App_KernelPantherDebugContainer.php') {
    touch(__DIR__.'/ContainerRMW2JcO.legacy');

    return;
}

if (!\class_exists(App_KernelPantherDebugContainer::class, false)) {
    \class_alias(\ContainerRMW2JcO\App_KernelPantherDebugContainer::class, App_KernelPantherDebugContainer::class, false);
}

return new \ContainerRMW2JcO\App_KernelPantherDebugContainer([
    'container.build_hash' => 'RMW2JcO',
    'container.build_id' => '24d6a4dc',
    'container.build_time' => 1636560132,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRMW2JcO');
