<?php

namespace Container5XZoBiR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S04YPmjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S04YPmj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S04YPmj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'catalog' => ['privates', '.errored..service_locator.S04YPmj.App\\Entity\\Catalog', NULL, 'Cannot autowire service ".service_locator.S04YPmj": it references class "App\\Entity\\Catalog" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'file' => ['privates', '.errored..service_locator.S04YPmj.App\\Entity\\File', NULL, 'Cannot autowire service ".service_locator.S04YPmj": it references class "App\\Entity\\File" but no such service exists.'],
            'product' => ['privates', '.errored..service_locator.S04YPmj.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.S04YPmj": it references class "App\\Entity\\Product" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.S04YPmj.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.S04YPmj": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'catalog' => 'App\\Entity\\Catalog',
            'em' => '?',
            'file' => 'App\\Entity\\File',
            'product' => 'App\\Entity\\Product',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
