<?php

namespace Container5XZoBiR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatalogFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CatalogFormType' shared autowired service.
     *
     * @return \App\Form\CatalogFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CatalogFormType.php';

        return $container->privates['App\\Form\\CatalogFormType'] = new \App\Form\CatalogFormType();
    }
}
