<?php

namespace ContainerX7y9Rat;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7WrUs_DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7WrUs.d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7WrUs.d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'catalog' => ['privates', '.errored..service_locator.7WrUs.d.App\\Entity\\Catalog', NULL, 'Cannot autowire service ".service_locator.7WrUs.d": it references class "App\\Entity\\Catalog" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'onixFile_directory' => ['privates', '.value.XibwmKv', 'get_Value_XibwmKvService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.7WrUs.d.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.7WrUs.d": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'catalog' => 'App\\Entity\\Catalog',
            'em' => '?',
            'onixFile_directory' => '?',
            'paginator' => '?',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
