<?php

namespace ContainerX7y9Rat;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateProductControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UpdateProductController' shared autowired service.
     *
     * @return \App\Controller\UpdateProductController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/UpdateProductController.php';

        $container->services['App\\Controller\\UpdateProductController'] = $instance = new \App\Controller\UpdateProductController();

        $instance->setContainer(($container->privates['.service_locator.Sh3oBYO'] ?? $container->load('get_ServiceLocator_Sh3oBYOService'))->withContext('App\\Controller\\UpdateProductController', $container));

        return $instance;
    }
}
