<?php

namespace ContainerXJvsESf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFile2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.W4WZv7c.App\Entity\File' shared service.
     *
     * @return \App\Entity\File
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.W4WZv7c": it references class "App\\Entity\\File" but no such service exists.');
    }
}
