<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVHexNyF\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVHexNyF/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerVHexNyF.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerVHexNyF\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerVHexNyF\App_KernelTestDebugContainer([
    'container.build_hash' => 'VHexNyF',
    'container.build_id' => '74f7756d',
    'container.build_time' => 1636548371,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVHexNyF');
