<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY9lee6f\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY9lee6f/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerY9lee6f.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerY9lee6f\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerY9lee6f\App_KernelTestDebugContainer([
    'container.build_hash' => 'Y9lee6f',
    'container.build_id' => '3e0ee7b4',
    'container.build_time' => 1636544864,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY9lee6f');
