<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'user_create' => [[], ['_controller' => 'App\\Controller\\CreateController::index'], [], [['text', '/create']], [], []],
    'user_delete' => [['id'], ['_controller' => 'App\\Controller\\DeleteController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete']], [], []],
    'deleteFiles' => [['user_id', 'files_id'], ['_controller' => 'App\\Controller\\DeleteController::deleteFiles'], [], [['variable', '/', '[^/]++', 'files_id', true], ['variable', '/', '[^/]++', 'user_id', true], ['text', '/delete']], [], []],
    'default' => [[], ['_controller' => 'App\\Controller\\HomepageController::index'], [], [['text', '/']], [], []],
    'user_homepage' => [[], ['_controller' => 'App\\Controller\\HomepageController::index'], [], [['text', '/homepage']], [], []],
    'user_list' => [[], ['_controller' => 'App\\Controller\\ListController::index'], [], [['text', '/list']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'user_update' => [['id'], ['_controller' => 'App\\Controller\\UpdateController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/update']], [], []],
    'upload_onix' => [['id'], ['_controller' => 'App\\Controller\\UploadFileController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/upload']], [], []],
    'view_file' => [['id'], ['_controller' => 'App\\Controller\\ViewFileController::view'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/view']], [], []],
];
