<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS9Jerap\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS9Jerap/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS9Jerap.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS9Jerap\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS9Jerap\App_KernelDevDebugContainer([
    'container.build_hash' => 'S9Jerap',
    'container.build_id' => '98a62413',
    'container.build_time' => 1637165623,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS9Jerap');
