<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDV1xcP2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDV1xcP2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDV1xcP2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDV1xcP2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDV1xcP2\App_KernelDevDebugContainer([
    'container.build_hash' => 'DV1xcP2',
    'container.build_id' => '86828399',
    'container.build_time' => 1636547370,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDV1xcP2');
