<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'create_catalog' => [['id'], ['_controller' => 'App\\Controller\\CreateCatalogController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/create/catalog']], [], []],
    'user_create' => [[], ['_controller' => 'App\\Controller\\CreateController::index'], [], [['text', '/create']], [], []],
    'user_delete' => [['id'], ['_controller' => 'App\\Controller\\DeleteController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete']], [], []],
    'delete_catalog' => [['user_id', 'id'], ['_controller' => 'App\\Controller\\DeleteController::deleteCatalog'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/catalog'], ['variable', '/', '[^/]++', 'user_id', true], ['text', '/delete']], [], []],
    'delete_product' => [['id_user', 'id_catalog', 'id_file', 'id'], ['_controller' => 'App\\Controller\\DeleteController::deleteProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product'], ['variable', '/', '[^/]++', 'id_file', true], ['text', '/file'], ['variable', '/', '[^/]++', 'id_catalog', true], ['text', '/catalog'], ['variable', '/', '[^/]++', 'id_user', true], ['text', '/delete']], [], []],
    'default' => [[], ['_controller' => 'App\\Controller\\HomepageController::index'], [], [['text', '/']], [], []],
    'user_homepage' => [[], ['_controller' => 'App\\Controller\\HomepageController::index'], [], [['text', '/homepage']], [], []],
    'user_list' => [[], ['_controller' => 'App\\Controller\\ListController::index'], [], [['text', '/list']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'user_update' => [['id'], ['_controller' => 'App\\Controller\\UpdateController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/update']], [], []],
    'upload_onix' => [['user_id', 'id'], ['_controller' => 'App\\Controller\\UploadFileController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/catalog'], ['variable', '/', '[^/]++', 'user_id', true], ['text', '/upload']], [], []],
    'view_catalog' => [['user_id'], ['_controller' => 'App\\Controller\\ViewCatalogController::view'], [], [['text', '/catalogs'], ['variable', '/', '[^/]++', 'user_id', true], ['text', '/view']], [], []],
    'view_product' => [['id_user', 'id'], ['_controller' => 'App\\Controller\\ViewProductsController::viewFile'], [], [['text', '/products'], ['variable', '/', '[^/]++', 'id', true], ['text', '/catalog'], ['variable', '/', '[^/]++', 'id_user', true], ['text', '/view']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
